apiVersion: apps/v1
kind: Deployment
metadata:
  name: Board
  namespace: Board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Board
  template:
    metadata:
      labels:
        app: Board
    spec:
      containers:
        - name: Board
          image: <IMAGE>
          ports:
            - containerPort: 8080
